export const en = {
  аnatomical: "Anatomical",
  cone: "Cone",
  weight: "Weight",
  shape: "Handle shape",
  layers: "Number of layers",
  size: "Proportions",
  main_desc_1:
    "Welcome to the table tennis store. You can buy ping pong rackets, bases, rubbers and all kinds of accessories at the best prices.",
  main_desc_2:
    "The high quality of unique products is multiplied by flawless and fast service. If you`re having trouble choosing a racket that matches your style of play, don`t worry. Experienced specialists will advise and select the equipment that will help you win points important for victory.",
  news_1:
    "We are working In this difficult time, we are working. Sending orders by Nova Poshta or Ukrposhta from the city of Cherkasy. Together to victory. Everything will be ...",
  news_2:
    "We carry out a free racket assembly from your chosen components with a quality guarantee. Delivery of goods to any point of Ukraine and abroad. If you want to know news about table tennis in Ukraine and other interesting information about the world of table tennis, take a look at the article section on our website. We understand that table tennis (ping pong) is not just a game, but an exciting hobby. Welcome!",
  price: "Price",
  speed: "Speed",
  control: "Control",
  news: "News",
  articles: "Articles",
  questions: "Questions",
  buy: "Buy",
  search: "Search",
  call: "Free in Ukraine",
  mode: "Monday - Friday, ",
  time: "from 9:00 to 18:00",
  sign: "Sign In",
  language: "Language",
  delivery: "Delivery",
  payment: "Payment",
  contacts: "Contacts",
  base: "Base",
  overlays: "Overlays",
  sponges: "Top sheets and sponges",
  rackets: "Rackets",
  balls: "Balls",
  accessories: "Accessories",
  grids: "Grids",
  glue: "Adhesives and Boosters",
  bags: "Bags",
  cases: "Cases",
  cloth: "Sportswear",
  books: "Videos and books",
  shoes: "Shoes",
  sales: "Promotions and discounts",
  souvenirs: "Souvenirs",
  faucets: "Faucets",
  base_desc_1:
    "When choosing bases, consider their speed characteristics. The slowest bases are defensive ones. They are in the DEF (Defensive) category and give excellent control in the game. The bases for the universal game can be found in the ALL (Allround) category. They have an excellent balance between speed and control. The fastest bases are the attacking ones, they are located in the OFF (OFFENSIVE) category. Table tennis blades are also categorized by speed. For example, the bases ALL are divided into ALL-, ALL and ALL+ (the slowest is ALL- and the fastest is ALL+). Read how to choose a table tennis blade.",
  vt_wood:
    "VT Wood Defense is designed specifically for the modern defender. It allows you to play very reliably in defense, while there is the possibility of a very quick transition to the counterattack. Due to its hardness, VT Wood Defense's five-ply blade is ideal for long-range defense while still allowing for quick counters. High quality workmanship and elegant appearance attract attention. The VT Wood Defense Blade is the perfect choice for a versatile defense that combines strong spins with fast top spins. The VT Wood Defense blade pairs well with all kinds of cleats, making it a formidable weapon for defensive play. VT Wood Defense has a 5-layer construction (kiri and stiffer limba outer layers). The structure of the VT Wood Defense blade is similar to the well-known BUTTERFLY Joo Se Hyuk blade. The VT Wood Defense range of exclusive bases are handcrafted using a special bonding technique that involves several types of adhesives (including a hidden adhesive that does not create an additional layer). The result is superior ball feel, durability and blade strength. The surface of the base is covered with a layer of varnish for reliable protection and prevention of tearing of fibers and chips. To protect against moisture and dirt, the base handle is also varnished.",
  vt_cork:
    "VT Wood Defense is designed specifically for the modern defender. It allows you to play very reliably in defense, while there is the possibility of a very quick transition to the counterattack. Due to its hardness, VT Wood Defense's five-ply blade is ideal for long-range defense while still allowing for quick counters. High quality workmanship and elegant appearance attract attention. The VT Wood Defense Blade is the perfect choice for a versatile defense that combines strong spins with fast top spins. The VT Wood Defense blade pairs well with all kinds of cleats, making it a formidable weapon for defensive play. VT Wood Defense has a 5-layer construction (kiri and stiffer limba outer layers). The structure of the VT Wood Defense blade is similar to the well-known BUTTERFLY Joo Se Hyuk blade. The VT Wood Defense range of exclusive bases are handcrafted using a special bonding technique that involves several types of adhesives (including a hidden adhesive that does not create an additional layer). The result is superior ball feel, durability and blade strength. The surface of the base is covered with a layer of varnish for reliable protection and prevention of tearing of fibers and chips. To protect against moisture and dirt, the base handle is also varnished.",
  vt_mahagon:
    "VT Mahagon is a wooden defensive blade with enhanced control and high precision play. The blade provides excellent ball feel. VT Mahagon has a 4-layer construction. The kiri center layer and the combination of tougher poplar and mahogany outer layers create an excellent balance of defensive performance. One of the sides of the base (darker, mahogany) is designed for attacking active play with 'forehand', and the other side (lighter, poplar) - for reliable protection with 'backhand'. The protective side of the blade Def has a low rebound coefficient, which slows down the ball. This allows it to be returned very short and above the grid itself. When playing with long spikes or anti-spin, a strong destructive effect is created, the maximum return of rotation to the opponent is ensured when playing with blocks and trimming. The trajectory of the ball is very low, which prevents the opponent from launching an attack. The base is handcrafted using a special bonding technique that involves several types of adhesive (including a hidden adhesive that does not create an additional layer). The handle is composed of alder, white poplar and cork. Cork helps to reduce base vibrations. The surface of the base is covered with a layer of varnish for reliable protection and prevention of tearing of fibers and chips.",
  vt_sapeli:
    "VT Sapeli Defense is designed specifically for the modern defender. It allows you to confidently attack and defend. This is the perfect choice for a varied defense that combines strong spins with fast top spins. With a top spin, the arc is low, which allows you to return the balls to the table. The VT Sapeli Defense blade works well with all kinds of pimples, making it a formidable weapon for defensive play. VT Sapeli Defense has a 5-layer construction (kiri and more rigid outer layers of sapeli). The structure of the VT Wood Sapeli blade is similar to the well-known BUTTERFLY Joo Se Hyuk blade. A series of exclusive bases VT Wood Defense is made by hand using a special gluing technology, which involves several types of glue. The result is superior ball feel, durability and blade strength. The surface of the base is covered with a layer of varnish for reliable protection and prevention of tearing of fibers and chips. To protect against moisture and dirt, the base handle is also varnished.",
  vt_combi:
    "VT Combi Wood Defense continues the series of popular exclusive blades and is designed specifically for the modern defender. It allows you to play very reliably in defense, while there is the possibility of a very quick transition to the counterattack. The central layer of the base is a cork that reduces vibrations. The outer layers of the base are different: sapele and walnut. The nut side is a bit slower and is great for backhand play (including pimples). High quality workmanship and elegant appearance attract attention. The VT Combi Wood Defense Blade is the perfect choice for a versatile defense that combines strong spins with fast top spins. The VT Combi Wood Defense blade pairs well with all kinds of spikes, making it a formidable weapon for defensive play. VT Combi Wood Defense has a 7-layer construction (cork and harder outer layers of poplar, walnut and sapele). A series of exclusive bases VT Wood Defense is made by hand using a special gluing technology, which involves several types of glue. The result is superior ball feel, durability and blade strength. The surface of the base is covered with a layer of varnish for reliable protection and prevention of tearing of fibers and chips. To protect against moisture and dirt, the base handle is also varnished.",
  vt_mahagon_def:
    "The VT Mahagon Def 2 is a woody defensive blade with good control for high precision play. The blade provides excellent ball feel. VT Mahagon Def 2 has a 4-layer construction. The ayus core and the combination of tougher poplar and mahogany outer layers create an excellent balance of defensive performance. Compared to the VT Mahagon Def blade, the VT Mahagon Def 2 blade is slightly faster. One of the sides of the base (darker, mahogany) is designed for attacking active play with 'forehand', and the other side (lighter, poplar) - for reliable protection with 'backhand'. The protective side of the blade Def has a low rebound coefficient, which slows down the ball.This allows it to be returned very short and above the grid itself. When playing with long spikes or anti-spin, a strong destructive effect is created, the maximum return of rotation to the opponent is ensured when playing with blocks and trimming. The trajectory of the ball is very low, which prevents the opponent from launching an attack. The base is made by hand using a special gluing technology, which involves several types of glue. The handle is composed of alder, abachi and mahogany wood. The surface of the base is covered with a layer of varnish for reliable protection and prevention of tearing of fibers and chips.",
  palio_def:
    "PALIO Chop #1 is the equivalent of the Butterfly Joo Se Hyuk blade and is designed specifically for today's defenders. It allows you to defend very confidently and stably, and at the same time attack unexpectedly and powerfully. The base structure is 5-layer. In it, the developers managed to choose a unique combination of wood layers that provide good ball control along with high speed in attack. Also, the blade PALIO Chop #1 provides excellent compatibility with all kinds of pimples and anti-spin rubbers. Base vibrations are reduced to the lowest possible level. The PALIO Chop #1 blade excels in undercutting and blocking, allowing you to surprise attack with top spins, spins and flats. For defensive style players, it is recommended to use long spikes (or anti spin) on one side of the racket and a smooth overlay on the other side. The PALIO Chop #1 blade is also great for allround players looking for stability in the game and for beginners. In this case, it is better to stick two smooth overlays on the base. Experience unique stability and good speed by playing with the PALIO Chop #1 blade.",
  yinhe_def:
    "Yinhe Def5 is a defensive blade with excellent control. Yinhe Def5 belongs to a series of popular Def series blades. The blade is specially designed for the demanding defender playing in a modern style. The Yinhe Def5 blade plays well in defense and at the same time allows you to sharply and unexpectedly attack, leaving no chance for the opponent. In addition, the blade of Yinhe Def5 gives unrivaled ball feel through the use of specially selected woods.",
  yinhe_n:
    "YINHE N10s ALL+ has an updated attractive design. The YINHE N10s ALL+ blade provides an excellent balance of gaming performance, giving the player truly unlimited possibilities for a variety of matching games. Added to this is the very high level of control inherent in the YINHE N10s ALL+ blade. With the YINHE N10s ALL+ blade, you can change your game pattern flexibly, surprising your opponent with a quick transition from confident and reliable defense to fast and unexpected attacks.",
  palio_b:
    "The balanced blade PALIO B31 will allow you to reach your full potential in versatile play. PALIO B31 will easily bring to life both the attacking and defensive components of your game. The 7-layer construction of the PALIO B31 blade will allow you to easily start any attacking actions, performing top spins and rolls. If necessary, you can confidently defend yourself by performing undercuts and blocks. Despite its rather modest price, the blade PALIO B31 has all the playing characteristics for a successful table tennis game. If your gaming strategy is allround, then PALIO B31 will be a great solution for you.",
  sanwei_all:
    "The Sanwei Accumulator S blade is perfect for versatile allround play with high ball control. And although the blade is between ALL+ and OFF- in terms of its speed characteristics, it has a very high stability in the game. The Sanwei Sanwei Accumulator S performs equally well in both a defensive game based on cuts and blocks and an attacking game, allowing you to powerfully and unexpectedly attack your opponent. With the Sanwei Accumulator S blade, you can play in a variety of ways, easily varying your actions. You will be able to play top spin, coast and straight punch, block or undercut with ease alternating any of the technical elements. The Sanwei Accumulator S pairs well with many smooth rubbers and spikes (long, medium and short). Therefore, it is also suitable for creating a combined racket with spikes. In addition to this, the Sanwei Accumulator S base has an unbeatable price-performance ratio.",
  palio_acn_all:
    "The popular 5-layer blade PALIO ACN belongs to the ALL+ category and allows you to play very diversely, varying your actions from defensive undercuts and blocks to attacking top spins and rolls. And yet, the strengths of the PALIO ACN blade are successful attacking play combined with high accuracy. In addition, the PALIO ACN provides an unrivaled feel for the ball in play. The versatility and excellent playing characteristics of this blade make it very attractive to table tennis enthusiasts. Add to this the excellent price-quality ratio inherent in this blade. Feel the ease in playing with the blade PALIO CAN, technically attacking and defending reliably when necessary.",
  globe_all:
    "This 5-ply blade is designed specifically for versatile play. It gives you a high level of control over any technique in table tennis. It plays equally well in defensive play based on cuts and blocks as well as in attacking play, allowing you to attack your opponent powerfully and unexpectedly. With the GLOBE 583 blade, you can easily perform top spins, rolls and straights. In addition to this, the GLOBE 583 has an unbeatable price-performance ratio.",
  yinhe_all:
    "Yinhe N-2s is the slowest blade of the popular N series blades. Its speed characteristics are approximately between ALL+ and OFF-. It has the highest level of control. Allows you to play very successfully in the style of Allround with the possibility of variable attacks. The blade of Yinhe N-2s combines the characteristics of speed, spin and control perfectly. By playing Yinhe N-2s you will be able to play in a variety of ways, surprising your opponent with a quick transition from defense to fast attack.",
  globe_whirl:
    "The Whirl Wind 581 is a 6.2mm thick five ply blade weighing 85g. It belongs to the all+ category. It is a powerful blade with good ball feel. Ideal value for money. Made in China.",
  sanwei_soft:
    "Battery C is a universal base. The classic structure gives him a great balance of stats in the game. This blade utilizes modern carbon blade manufacturing techniques that allow for a controlled attacking game. The SANWEI Accumulator C is an upgraded version of the classic SANWEI 502E Soft Carbon blade. Affordable price with excellent performance! If carbon attack blades are too fast for you, then the SANWEI Accumulator C is the perfect choice.",
  yinhe_earth:
    "YINHE Earth E-3 is a balanced blade with brilliant offensive capabilities and a high level of control. Allows you to play in an aggressive manner, while maintaining an excellent sense of the ball. According to its speed characteristics, YINHE Earth E-3 belongs to the ALL + (fast all-round) category. Top spins, rolls, executed with a soft feeling of the ball, will allow you to play almost flawlessly and easily outplay your opponent. YINHE Earth E-3 provides good compatibility with relatively hard rubbers. Experience the soft feel of the YINHE Earth E-3 in a real match.",
  palio_off:
    "PALIO Energy 01 is a balanced OFF blade with excellent ball control. The PALIO Energy 01 features a unique three-layer construction that allows for a variety of table tennis play. The special selection of wood layers in the construction of the PALIO Energy 01 blade allows you to get an excellent ball feel. PALIO Energy 01 allows you to easily alternate a variety of attacks with defensive play, easily varying various technical elements. Despite the rather low price, the PALIO Energy 01 base is in no way inferior to expensive bases from famous brands.",
  globe_wind:
    "The base of the Whirl Wind 783 consists of 7 layers of wood and is 6.4 mm thick. It has high power and energy in attack and at the same time has high control. Ideal for fast spin attacks and top spins close to the table and in the middle zone. Made in China.",
  yinhe_n:
    " YINHE N-1s is an attacking blade with excellent control and good speed. It's great for attacking players. The 5-layer construction of the YINHE N-1s blade, made of specially selected layers of wood, allows you to play precisely in place and with high stability. The center layer of YINHE N-1s is abachi wood and the outer layers are limba. This design allows you to play with high stability and high speed. With the blade YINHE N-1s you will be able to play confidently, feeling secure when playing defense, and at the slightest opportunity to switch to a sharp and unexpected attack. The base of YINHE N-1s has an attractive design. Add to that the unrivaled value for money that comes with the YINHE N-1s blade. Experience the balanced YINHE N-1s blade in the game.",
  palio_energy:
    "The PALIO Energy 03 Carbon offensive blade is OFF-rated and designed to play with the new 40+ balls. The blade construction uses four layers of carbon for unsurpassed speed performance. The PALIO Energy 03 Carbon blade makes it very easy to start an attack and gives you the ability to keep your opponent under constant Despite the fact that PALIO Energy 03 has an attacking breed, it allows you to confidently defend with a block or undercut if necessary.",
  palio_energy_4:
    "The attacking blade PALIO Energy 04 belongs to the OFF category and is designed to play with the new 40+ balls. The construction of the blade uses two carbon layers, providing high speed characteristics. PALIO Energy 04 is great for attacking players who want good ball control. Despite the fact that PALIO Energy 04 has an attacking breed, it allows you to confidently defend with a block or undercut if necessary.",
  globe_whirl:
    "The Whirl Wind 582 is a 6.6mm thick 5 ply blade and weighs about 80g. It belongs to the category of attacking off. It is a powerful blade with good ball feel. Allows you to successfully play in the attack with top spin and coast. Has high control. Ideal value for money. Made in China.",
  enlight:
    "729 Enlight is a novelty from the well-known manufacturer 729, which has already gained popularity among table tennis fans for its excellent value for money. The characteristics of the blade are great for the attacking player looking for a compromise between speed and control. 729 Enlight OFF - allows you to play in a variety of ways, either a little from the table with a top spin, or close to the table, technically attacking with a coast and a direct hit.",
  sanwei_off:
    "Attack blade made of wood, specially designed for a variety of offensive play. Thanks to the use of outer layers of ayusa wood, the base gives excellent control and rotation. The classic 5-layer structure provides high accuracy and good offensive capabilities. This fast blade is ideal for spinning players who expect speed, control and accuracy from the blade.",
  carbon_palio:
    "The attacking blade PALIO Energy 04 belongs to the OFF category and is designed to play with the new 40+ balls. The construction of the blade uses two carbon layers, providing high speed characteristics. PALIO Energy 04 is great for attacking players who want good ball control. Despite the fact that PALIO Energy 04 has an attacking breed, it allows you to confidently defend with a block or undercut if necessary.",
  carbon_palio_energy:
    "The attacking blade PALIO Energy 03 Carbon belongs to the OFF category and is designed to play with the new 40+ balls. The construction of the blade uses four carbon layers, providing unsurpassed speed characteristics. The PALIO Energy 03 Carbon blade makes it very easy to launch an attack and gives you the ability to keep your opponent under constant attacking pressure. Despite the fact that PALIO Energy 03 has an attacking breed, it allows you to confidently defend with a block or undercut if necessary.",
  sanwei_carbon:
    "Battery C is a universal base. The classic structure gives him a great balance of stats in the game. This blade utilizes modern carbon blade manufacturing techniques that allow for a controlled attacking play. SANWEI Accumulator C is an updated version of the classic SANWEI 502E Soft Carbon blade. Affordable price with excellent performance! If carbon attack blades are too fast for you, then the SANWEI Accumulator C is the perfect choice.",
  palio_carbon:
    "This popular attacking blade from Palio excels in offense and provides excellent speed dynamics. Playing with the PALIO T3 Carbon blade, you can easily show your strengths by performing top spins, rolls or straight shots. The presence of carbon layers in the construction of the blade provides sufficient speed and the formation of the maximum zone of the best rebound on the playing surface of the blade. The center layer of the base is softer and this creates a high level of control. When playing with this blade, you can literally “feel” the ball and send it to any point on the table at high speed. The advantages of PALIO T3 Carbon also include an unsurpassed price-quality ratio.",
  friend:
    "The 729 V5 carbon blade gives you good speed and control in the game. The base is classified as OFF-. The presence of two layers of energy carbon provides high attacking power. With the blade 729 V5 you will be able to confidently attack, performing top spins, rolls and other elements. All components are produced without difficulty and with very high stability.",
  sanwei_shrafton:
    "The Sanwei Shrafton could be your first carbon blade. A balanced sense of speed and control will make your game progress easier than ever. The beech surface and LD carbon in the blade construction give a good feel on impact and help you play more aggressively. In addition, the percentage of errors in the game will decrease. The base allows for very powerful ball returns with ease. Experience the Sanwei Shrafton blade in the game, which will take you to the next level.",
  mercury:
    "The fast and dynamic Yinhe Mercury Y-12 Carbon blade allows you to realize any of your attacking ideas. Thanks to the unique 7-layer construction, the Yinhe Mercury Y-12 not only has good speed, but also provides excellent ball control. The use of two layers of energy carbon and the careful selection of woods in the construction of the blade creates an excellent balance between speed and ball feel. Experience speed and superior dynamics with the Yinhe Mercury Y-12 blade.",
  sanwei_c:
    "A sharp attacking blade specially designed for versatile offensive play. This fast and light blade is ideal for spinning players who expect high speed, control and accuracy from the blade. The construction of the blade uses a special type of carbon LD Carbon, which gives power and high precision. The unique fine ball feel of the SANWEI C5 LD Carbon creates the perfect blade.",
}
