import bcrypt from "bcryptjs"

const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  base: [
    {
      category: "DEF",
      group: "VT",
      item_id: 1,
      img: "/static/images/products/base/def/vt_wood.png",
      name: "VT Wood Defence",
      path: "vt_wood_defence",
      price: 2850,
      weight: 85,
      shape: "cone",
      desc: "vt_wood",
      speed: 73,
      control: 95,
      layers: 5,
      height: 5.6,
      width: "154мм х 165мм",
      shape_length: 105,
      countInStock: 10,
    },
    {
      category: "DEF",
      group: "VT",
      item_id: 2,
      img: "/static/images/products/base/def/vt_cork.png",
      name: "VT Wood Defence Cork",
      path: "vt_wood_cork",
      price: 2850,
      weight: 90,
      shape: "cone",
      desc: "vt_cork",
      speed: 71,
      control: 96,
      layers: 5,
      height: 5.5,
      width: "151мм х 157мм",
      shape_length: 108,
      countInStock: 10,
    },
    {
      category: "DEF",
      group: "VT",
      item_id: 3,
      img: "/static/images/products/base/def/vt_mahagon.png",
      name: "VT Mahagon Def",
      path: "vt_mahagon",
      price: 2850,
      weight: 75,
      shape: "cone",
      desc: "vt_mahagon",
      speed: 77,
      control: 98,
      layers: 4,
      height: 5.5,
      width: "154мм х 165мм",
      shape_length: 108,
      countInStock: 10,
    },
    {
      category: "DEF",
      group: "VT",
      item_id: 4,
      img: "/static/images/products/base/def/vt_sapeli.png",
      name: "VT Sapeli Defence",
      path: "vt_sapeli",
      price: 2850,
      weight: 85,
      shape: "cone",
      desc: "vt_sapeli",
      speed: 77,
      control: 95,
      layers: 5,
      height: 5.6,
      width: "154мм х 165мм",
      shape_length: 105,
      countInStock: 10,
    },
    {
      category: "DEF",
      group: "VT",
      item_id: 5,
      img: "/static/images/products/base/def/vt_combi.png",
      name: "VT Combi Wood Defence",
      path: "vt_combi",
      price: 2850,
      weight: 90,
      shape: "cone",
      desc: "vt_combi",
      speed: 74,
      control: 95,
      layers: 7,
      height: 4.9,
      width: "154мм х 162мм",
      shape_length: 103,
      countInStock: 10,
    },
    {
      category: "DEF",
      group: "VT",
      item_id: 6,
      img: "/static/images/products/base/def/vt_mahagon_2.png",
      name: "VT Mahagon Def 2",
      path: "vt_mahagon_2",
      price: 2850,
      weight: 87,
      shape: "cone",
      desc: "vt_mahagon_def",
      speed: 79,
      control: 98,
      layers: 4,
      height: 5.8,
      width: "154мм х 165мм",
      shape_length: 105,
      countInStock: 10,
    },
    {
      category: "DEF",
      group: "PALIO",
      item_id: 7,
      img: "/static/images/products/base/def/palio.png",
      name: "PALIO Chop #1",
      path: "palio_chop",
      price: 990,
      shape: "cone",
      desc: "palio_def",
      speed: 73,
      control: 98,
      layers: 4,
      height: 5.8,
      width: "157мм х 160мм",
    },
    {
      category: "DEF",
      group: "YINHE",
      item_id: 8,
      img: "/static/images/products/base/def/yinhe.png",
      name: "Yinhe Def5",
      path: "yinhe_def",
      price: 1017,
      shape: "cone",
      desc: "yinhe_def",
      countInStock: 10,
    },

    {
      category: "ALL",
      group: "Yinhe",
      item_id: 9,
      img: "/static/images/products/base/all/yinhe.png",
      name: "GALAXY YINHE N10s ALL+",
      path: "galaxy_yinhe",
      price: 498,
      weight: 85,
      shape: "cone",
      desc: "yinhe_n",
      layers: 5,
      countInStock: 10,
    },
    {
      category: "ALL",
      item_id: 10,
      group: "Palio",
      img: "/static/images/products/base/all/palio_31.png",
      name: "PALIO B31",
      path: "palio_b",
      price: 540,
      shape: "cone",
      desc: "palio_b",
      speed: 89,
      control: 85,
      countInStock: 10,
    },
    {
      category: "ALL",
      item_id: 11,
      group: "Sanwei",
      img: "/static/images/products/base/all/sanwei.png",
      name: "Sanwei Accumulator S",
      path: "sanwei_accumulator",
      price: 540,
      shape: "cone",
      desc: "sanwei_all",
      speed: 8,
      control: 9,
      layers: 5,
      countInStock: 10,
    },
    {
      category: "ALL",
      item_id: 12,
      group: "Palio",
      img: "/static/images/products/base/all/palio_acn.png",
      name: "PALIO ACN ALL+",
      path: "palio_acn",
      price: 585,
      shape: "cone",
      desc: "palio_acn_all",
      speed: 85,
      control: 87,
      countInStock: 10,
    },
    {
      category: "ALL",
      item_id: 13,
      group: "Globe",
      img: "/static/images/products/base/all/globe.png",
      name: "GLOBE 583",
      path: "globe_583",
      price: 448.5,
      new_price: 600,
      shape: "анатомическая",
      desc: "globe_all",
      layers: 5,
      countInStock: 10,
    },
    {
      category: "ALL",
      item_id: 14,
      group: "Yinhe",
      img: "/static/images/products/base/all/yinhe_n.png",
      name: "Yinhe N-2s",
      path: "yinhe_n",
      price: 673.5,
      weight: 85,
      shape: "cone",
      desc: "yinhe_all",
      layers: 5,
      countInStock: 10,
    },
    {
      category: "ALL",
      item_id: 15,
      group: "Globe",
      img: "/static/images/products/base/all/globe_whirl.png",
      name: "GLOBE Whirl Wind 581",
      path: "globe_whirl",
      price: 748.5,
      weight: 85,
      shape: "cone",
      desc: "globe_whirl",
      speed: 85,
      control: 85,
      height: 6.2,
      countInStock: 10,
    },
    {
      category: "ALL",
      item_id: 16,
      group: "Sanwei",
      img: "/static/images/products/base/all/sanwei_soft.png",
      name: "SANWEI Accumulator C Soft Carbon",
      path: "sanwei_soft",
      price: 823.5,
      new_price: 599.0,
      weight: 85,
      shape: "cone",
      desc: "sanwei_soft",
      countInStock: 10,
    },
    {
      category: "ALL",
      item_id: 17,
      group: "Yinhe",
      img: "/static/images/products/base/all/yinhe_earth.png",
      name: "YINHE Earth E-3",
      path: "yinhe_earth",
      price: 949,
      layers: 5,
      shape: "cone",
      desc: "yinhe_earth",
      countInStock: 10,
    },

    {
      category: "OFF",
      item_id: 18,
      group: "Palio",
      img: "/static/images/products/base/off/palio.png",
      name: "PALIO Energy 01",
      path: "palio_energy",
      price: 540,
      height: 7.2,
      shape: "CPen",
      desc: "palio_off",
      layers: 3,
      speed: 90,
      control: 88,
      countInStock: 10,
    },
    {
      category: "OFF",
      item_id: 19,
      group: "Globe",
      img: "/static/images/products/base/off/globe_wind.png",
      name: "GLOBE Whirl Wind 783",
      path: "globe_whirl",
      price: 600,
      new_price: 399,
      shape: "cone",
      desc: "globe_wind",
      speed: 100,
      control: 80,
      countInStock: 10,
    },
    {
      category: "OFF",
      item_id: 20,
      group: "Yinhe",
      img: "/static/images/products/base/off/yinhe_n.png",
      name: "YINHE N-1s",
      path: "yinhe_n",
      price: 720,
      height: 6.5,
      shape: "cone",
      desc: "yinhe_n",
      layers: 5,
      countInStock: 10,
    },
    {
      category: "OFF",
      item_id: 21,
      group: "Palio",
      img: "/static/images/products/base/off/palio_energy.png",
      name: "PALIO Energy 03 Carbon",
      path: "palio_carbon",
      price: 768,
      new_price: 699,
      height: 7.0,
      shape: "cone",
      desc: "palio_energy",
      speed: 95,
      control: 87,
      layers: 5,
      countInStock: 10,
    },
    {
      category: "OFF",
      item_id: 22,
      group: "Palio",
      img: "/static/images/products/base/off/palio_energy_4.png",
      name: "PALIO Energy 04 Carbon",
      path: "palio_energy_4",
      price: 768,
      height: 6.9,
      shape: "cone",
      desc: "palio_energy_4",
      speed: 93,
      control: 87,
      layers: 5,
      countInStock: 10,
    },
    {
      category: "OFF",
      item_id: 23,
      group: "Globe",
      img: "/static/images/products/base/off/globe_whirl.png",
      name: "GLOBE Whirl Wind 582",
      path: "globe_whirl_wind",
      price: 822,
      new_price: 748.5,
      shape: "cone",
      desc: "globe_whirl",
      layers: 5,
      speed: 95,
      control: 80,
      countInStock: 10,
    },
    {
      category: "OFF",
      item_id: 24,
      group: "729",
      img: "/static/images/products/base/off/enlight.png",
      name: "729 Enlight",
      path: "enlight",
      price: 825,
      height: 6.0,
      weight: 83,
      shape: "cone",
      desc: "enlight",
      layers: 5,
      countInStock: 10,
    },
    {
      category: "OFF",
      item_id: 25,
      group: "Sanwei",
      img: "/static/images/products/base/off/sanwei.png",
      name: "SANWEI TS 7",
      path: "sanwei_ts",
      price: 898.5,
      weight: 85,
      shape: "cone",
      desc: "sanwei_off",
      layers: 5,
      countInStock: 10,
    },

    {
      category: "Carbon",
      item_id: 26,
      group: "Palio",
      img: "/static/images/products/base/carbon/palio.png",
      name: "PALIO Energy 04 Carbon",
      path: "palio_energy_carbon_4",
      price: 768,
      height: 6.9,
      shape: "cone",
      desc: "carbon_palio",
      layers: 5,
      speed: 93,
      control: 87,
      countInStock: 10,
    },
    {
      category: "Carbon",
      item_id: 27,
      group: "Palio",
      img: "/static/images/products/base/carbon/palio_energy.png",
      name: "PALIO Energy 03 Carbon",
      path: "palio_energy_carbon_3",
      price: 768,
      new_price: 699,
      layers: 5,
      height: 7.0,
      shape: "cone",
      desc: "carbon_palio_energy",
      speed: 95,
      control: 87,
      countInStock: 10,
    },
    {
      category: "Carbon",
      item_id: 28,
      group: "Sanwei",
      img: "/static/images/products/base/carbon/sanwei.png",
      name: "SANWEI Accumulator C Soft Carbon",
      path: "sanwei_soft_carbon",
      price: 823.5,
      new_price: 599,
      weight: 85,
      shape: "cone",
      desc: "sanwei_carbon",
      layers: 5,
      countInStock: 10,
    },
    {
      category: "Carbon",
      item_id: 29,
      group: "Palio",
      img: "/static/images/products/base/carbon/palio_carbon.png",
      name: "PALIO T3 Carbon",
      path: "palio_carbon",
      price: 900,
      shape: "cone",
      desc: "palio_carbon",
      speed: 90,
      control: 88,
      layers: 5,
      countInStock: 10,
    },
    {
      category: "Carbon",
      item_id: 30,
      group: "729",
      img: "/static/images/products/base/carbon/friend.png",
      name: "FRIENDSHIP RITC 729 V5",
      path: "friendship",
      price: 900,
      new_price: 725,
      height: 6.4,
      shape: "cone",
      desc: "friend",
      speed: 8,
      control: 10,
      layers: 5,
      width: "158мм х 150мм",
      countInStock: 10,
    },
    {
      category: "Carbon",
      item_id: 31,
      group: "Sanwei",
      img: "/static/images/products/base/carbon/sanwei_carbon.png",
      name: "SANWEI Shrafton Carbon",
      path: "sanwei_shrafton",
      price: 973.5,
      height: 7.0,
      weight: 80,
      shape: "cone",
      desc: "sanwei_shrafton",
      layers: 5,
      width: "157мм х 150мм",
      countInStock: 10,
    },
    {
      category: "Carbon",
      item_id: 32,
      group: "Yinhe",
      img: "/static/images/products/base/carbon/mercury.png",
      name: "Yinhe Mercury Y-12 Carbon",
      path: "yinhe_mercury",
      price: 1020,
      weight: 88,
      shape: "cone",
      desc: "mercury",
      layers: 5,
      countInStock: 10,
    },
    {
      category: "Carbon",
      item_id: 33,
      group: "Sanwei",
      img: "/static/images/products/base/carbon/sanwei_c.png",
      name: "SANWEI C5 LD Carbon",
      path: "sanwei_c_5",
      price: 1048.5,
      weight: 85,
      shape: "cone",
      desc: "sanwei_c",
      layers: 5,
      countInStock: 10,
    },
  ],
}

export default data
